# Generated by Django 2.2.4 on 2020-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_host',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mail_port',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
