# Generated by Django 2.2.4 on 2020-01-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20200109_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
