# Generated by Django 2.2.4 on 2020-01-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_customuser_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twilio_account_sid',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twilio_auth_token',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
