# Generated by Django 2.2.4 on 2020-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20200119_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twilio_phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
