# Generated by Django 2.2.4 on 2020-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_customuser_twilio_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlsend',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
