# Generated by Django 2.2.4 on 2020-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20200415_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twilio_phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
