# Generated by Django 2.2.4 on 2020-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20200415_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='messages_amount',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parse_tiu_amount',
            field=models.IntegerField(default=0),
        ),
    ]
