# Generated by Django 2.2.4 on 2020-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_auto_20200417_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('our_file', models.FileField(upload_to='../mailer/client_databases')),
                ('file_owner', models.CharField(max_length=80, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parse_avito_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parse_youla_amount',
            field=models.IntegerField(default=0),
        ),
    ]
