# Generated by Django 2.2.4 on 2020-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_auto_20200419_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientparsing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clientparsing',
            name='our_file',
        ),
        migrations.AddField(
            model_name='clientparsing',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
