# Generated by Django 2.2.4 on 2020-04-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_auto_20200419_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parse_youla_amount',
        ),
    ]
