# Generated by Django 2.2.4 on 2020-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_remove_customuser_parse_youla_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unparsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unsent',
            field=models.IntegerField(default=0),
        ),
    ]
