# Generated by Django 2.2.4 on 2020-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0020_customuser_templates_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlSendFromConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('file_owner', models.CharField(max_length=80, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
