# Generated by Django 2.2.4 on 2020-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0021_htmlsendfromconstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlsend',
            name='our_file',
            field=models.FileField(upload_to='mail/templates/sending-templates'),
        ),
    ]
