# Generated by Django 2.2.4 on 2020-05-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0022_auto_20200502_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_sum_amount',
            field=models.IntegerField(default=0),
        ),
    ]
